run:
  timeout: 5m

output:
  format: github-actions

linters:
  disable-all: true
  enable:
    # default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # non-default linters
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - errchkjson
    - errname
    - errorlint
    - gofmt
    - lll
    - nilerr
    - nosprintfhostport
    - revive
    - tenv
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  lll:
    line-length: 120
    tab-width: 4

  revive:
    ignore-generated-header: true
    severity: error
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-naming
        disabled: true # covered by errname
      - name: error-strings
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
