run:
  timeout: 5m

output:
  format: github-actions

linters:
  disable-all: true
  enable:
    # default linters
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck

    # non-default linters
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - errchkjson
    - errname
    - errorlint
    - gofmt
    - lll
    - nilerr
    - nosnakecase
    - nosprintfhostport
    - tenv
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
