name: Lint Github workflows

on:
  workflow_call:

jobs:
  lint:
    name: Lint Github workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint workflows
        uses: docker://rhysd/actionlint:latest
        with:
          args: >-
            -color
            -ignore "value \"true\" in \"exclude\" does not match in matrix \"disabled\" combinations"
