name: Lint Github workflows

on:
  workflow_call:

jobs:
  lint:
    name: Lint Github workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Lint workflows
        uses: docker://rhysd/actionlint:latest
        with:
          args: >-
            -color
            -ignore "value \"true\" in \"exclude\" does not match in matrix \"disabled\" combinations"
