on:
  workflow_call:

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: ['ubuntu', 'macos', 'windows']
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        check-latest: true
    - name: Install gotestsum
      run: |
        go install gotest.tools/gotestsum@v1
    - name: Run Test Suite
      run: |
        gotestsum -- -race -coverpkg=./... -coverprofile=coverprofile -covermode=atomic ./...
      env:
        GOTESTSUM_JSONFILE: gotestsum.json
    - name: Annotate Test Suite Results
      if: ${{ (success() || failure()) && hashFiles('gotestsum.json') != '' }}
      uses: guyarb/golang-test-annotations@v0.6.0
      with:
        test-results: gotestsum.json
    - name: Start Uploading Coverage Report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverprofile
        flag-name: go${{ steps.setup-go.outputs.go-version }}-${{ matrix.os }}
        parallel: true

  finalize:
    name: Finalize
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Uploading Coverage Report
        uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
